<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-OI9FLFD4" ignored="0" name="Test" tests="4" failures="1" timestamp="2020-07-20T02:01:37 IST" time="59.922" errors="0">
  <testcase name="cityWeather" time="12.193" classname="ndtvUI.NDTVWeatherPage"/>
  <testcase name="validateTemp" time="0.002" classname="openweatherAPI.CurrentWeatherData">
    <failure type="java.lang.AssertionError" message="expected [35] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [35] but found [0]
at openweatherAPI.CurrentWeatherData.validateTemp(CurrentWeatherData.java:50)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- validateTemp -->
  <testcase name="validateWithVarianceLogic" time="0.001" classname="openweatherAPI.CurrentWeatherData"/>
  <testcase name="GetCurrentWeatherData" time="5.198" classname="openweatherAPI.CurrentWeatherData"/>
</testsuite> <!-- Test -->
